### ISSUE TITLE
wireframe of the website

### ISSUE THREAD

**Issue by Akash-Kunwar** [KavachNetworks/Payroll_Manager_DOCS_Team-2020T0001#8]

**Comment by anant423** [comment]
Wireframes for our project
https://github.com/KavachNetworks/Payroll_Manager_DOCS_Team-2020T0001/tree/master/pencil_wireframe

**Comment by Akash-Kunwar** [comment]
[Wireframe link](https://github.com/KavachNetworks/Payroll_Manager_DOCS_Team-2020T0001/tree/master/pencil_wireframe)

**Comment by Akash-Kunwar** [comment]
Completed
